### ISSUE TITLE
geom_mosaic's `alpha` clashes with psych's `alpha`

### ISSUE THREAD

**Issue by Rmadillo** [haleyjeppson/ggmosaic#14]
If you have `psych` loaded (which is now a tidyverse autoload, I believe, via `broom`), `geom_mosaic` throws this error:

```
Error in alpha(data$fill, data$alpha) : 
  Data must either be a data frame or a matrix
```

Unloading `psych` dependencies and then unloading `psych` makes it work, because of the `alpha` function. 

Specifying `scales::alpha()` in your code should fix this?

 ```
 draw_panel = function(data, panel_scales, coord) {
  #  cat("draw_panel in GeomMosaic\n")
 # browser()
    if (all(is.na(data$colour)))
      data$colour <- scales::alpha(data$fill, data$alpha) # regard alpha in colour determination
```

**Comment by haleyjeppson** [comment]
Thanks for the suggestion. The change has been made.
