### ISSUE TITLE
Avoid exporting as_tibble.list

### ISSUE THREAD

**Issue by jennybc** [haleyjeppson/ggmosaic#21]
I have a bug report on readxl that I believe originates in the `as_tibble.list()` method exported here (https://github.com/tidyverse/readxl/issues/482).

https://github.com/haleyjeppson/ggmosaic/blob/9c88d627b8b50432e00918ccd6a3405477257f83/R/scale-product.R#L83-L97

Unfortunately, I can't reproduce the OP's issue because he did not provide his `test.xlsx` file. But the spreadsheet must have some combination of missing/duplicated columns that creates a list that is an edge case for your code intended to "not accidentally hijack a real list vector".

I don't understand this package well enough to know why you have `as_tibble.list()`. But I think it's not a good practice to export a method (a list method, in this case) that masks a method provided by the package that owns the generic (`as_tibble()` and the tibble package, in this case).

Can you create an S3 class for whatever list-y output you need special handling for (e.g. `mosaic_list`) and create an `as_tibble()` method for that instead (e.g. `as_tibble.mosaic_list`)?

**Comment by haleyjeppson** [comment]
This issue has been fixed (a big thank you to @earowang !!) and we are no longer hijacking as_tibble.list()
