### ISSUE TITLE
"Error in is.finite(x) : default method not implemented for type 'list'"

### ISSUE THREAD

**Issue by Slendyroal** [haleyjeppson/ggmosaic#25]
When I use the example, error message shows: "Error in is.finite(x) : default method not implemented for type 'list'"

> dim(matriz)
[1] 29 15
> dim (rasgos)
[1] 15  4

data=data.frame()

for ( i in 1:ncol(rasgos))
  
{
  
  x = rasgos[,i]
  
  for (k in 1:nrow(matriz))
    
  {
    
    wt = matriz[k, ]
    
    P29<- CWV(x,wt)
    
    data[k, i]<-P29
    
  }
  
}

Error in is.finite(x/wt) : default method not implemented for type 'list'

I am running R - 3.3.2 on  Windows.
> packageVersion("ggplot2")
[1] ‘3.0.0’
> packageVersion("ggmosaic")
[1] ‘0.2.0’

Pleasee help!

**Comment by haleyjeppson** [comment]
This issue is fixed with current versions of ggmosaic and ggplot2.
