### ISSUE TITLE
outline color does not appear in legend

### ISSUE THREAD

**Issue by mkoohafkan** [haleyjeppson/ggmosaic#27]
When you plot a `geom_mosaic` and specify an outline color with the `color` argument, the outline does not show up on the legend. Trying to force it using `override.aes` doesn't seem to work either.
```
library(ggmosaic)
ggplot(data = fly) + 
  geom_mosaic(aes(x = product(RudeToRecline), fill = DoYouRecline), color = "black")
# no black outline on legend
last_plot() + guides(fill = guide_legend(override.aes = list(color = "black")))
# still no black outline on legend
```

**Comment by haleyjeppson** [comment]
Thanks for bringing this to my attention! This issue has now been fixed.
