### ISSUE TITLE
Improving vignette

### ISSUE THREAD

**Issue by larmarange** [haleyjeppson/ggmosaic#29]
Results of call to `grid_arrange_shared_legend()` for divider functions and following examples are not displayed on the vignette.

See https://cran.r-project.org/web/packages/ggmosaic/vignettes/ggmosaic.html

**Comment by larmarange** [comment]
When checking the Rmd of the vignette, `eval` is currently set to `FALSE`. Is there a specific reason for that?

**Comment by haleyjeppson** [comment]
The vignette has been updated but the updates will not be seen at that site until the next CRAN update.

**Comment by larmarange** [comment]
Thanks
