### ISSUE TITLE
Make "RudeTo" variables factor levels consistent

### ISSUE THREAD

**Issue by gsimchoni** [haleyjeppson/ggmosaic#33]
Hi and thanks for a great package!

It seems like there is some inconsistency in the `fly` dataset "RudeTo" variables factor levels:

```r
levels(fly$RudeToBringBaby)
# [1] "No, not at all rude" "Yes, somewhat rude"  "Yes, very rude"     
levels(fly$RudeToRecline)
# [1] "Yes, very rude"      "Yes, somewhat rude"  "No, not rude at all"
```
Difference (1): the order is different --> might want to have them as ordered factors

Difference (2): the "No" level label is different, "No, not at all rude" vs. "No, not rude at all"

Why is (2) a problem?

Because it makes remedying (1) harder, in case you'd like two different mosaics, ordered the same. This will give you wrong result:

```r
fly %>% count(RudeToRecline)
```

```
# A tibble: 4 x 2
  RudeToRecline           n
  <fct>               <int>
1 Yes, very rude         71
2 Yes, somewhat rude    281
3 No, not rude at all   502
4 NA                    186
```

```r
fly2 <- fly %>% mutate(RudeToRecline = factor(RudeToRecline, levels = levels(RudeToBringBaby), ordered = TRUE))
fly2 %>% count(RudeToRecline)
```

```
# A tibble: 3 x 2
  RudeToRecline          n
  <ord>              <int>
1 Yes, somewhat rude   281
2 Yes, very rude        71
3 NA                   688
```

**Comment by haleyjeppson** [comment]
Hi @gsimchoni, thank you for the great suggestions. 

I definitely agree with you on (1) and will modify the direction of the levels to make the direction consistent throughout the data set. 

As for (2), that is a result of the design of the survey that produced the data. You can find the CSV I used from fivethirtyeight [here](https://github.com/fivethirtyeight/data/blob/master/flying-etiquette-survey/flying-etiquette.csv).
