### ISSUE TITLE
need documentation for the fill variable

### ISSUE THREAD

**Issue by under-score** [haleyjeppson/ggmosaic#38]
Would like to set the color of the blocks by the percentage of a third variable not included in the aes() statement. How can I do that?
`ggplot(data = phd) +  geom_mosaic(aes(x = product(V1, V2) ), na.rm=TRUE, fill=V3)`

**Comment by heike** [comment]
Could you please provide a reproducible example?

From your code I don't see why you can't include a mapping to fill color,
like

ggplot(data = phd) + geom_mosaic(aes(x = product(V1, V2), fill=V3),
na.rm=TRUE)
HTH,

Heike

**Comment by under-score** [comment]
thank you. Here is a stripped down example

```
phd <- setNames( data.frame(
  as.character(runif(100)>.5),
  as.character(runif(100)>.4),
  as.character(runif(100)>.6)
), c("V1", "V2", "V3"))

```

**Comment by haleyjeppson** [comment]
Hi @under-score, 

If you are wanting to include a mapping to fill color, it needs to go inside the `aes()` statement.

**Comment by under-score** [comment]
Would be nice to see a solution to my example.

**Comment by haleyjeppson** [comment]
Perhaps I am not understanding your question -- Is this what you are asking for? 

`ggplot(data = phd) + geom_mosaic(aes(x = product(V1, V2), fill=V3))`

**Comment by under-score** [comment]
sorry, can't remember several months later why I needed to fill outside of aes(). Maybe because there was some externally calculated fill variable, like a gradient from small to big mosaic.
