### ISSUE TITLE
CRAN update

### ISSUE THREAD

**Issue by ibecav** [haleyjeppson/ggmosaic#45]
Hi,

Wondering if the new changes will be pushed to CRAN any time soon.  The CRAN version seems to still be at 2.0.0 from 2018.  I'm hoping to upgrade my packages as well.  Thank you.

**Comment by GegznaV** [comment]
Any chances to see the updated version on CRAN soon?

**Comment by Generalized** [comment]
Definitely, it would be really nice to have the newest update available on CRAN!  @haleyjeppson

**Comment by haleyjeppson** [comment]
I am sorry to have kept you all waiting. The newest update is now available on CRAN!

**Comment by briatte** [comment]
No need to apologise :) This is a great package! Happy it's been updated on CRAN.
