### ISSUE TITLE
No level names on the axes

### ISSUE THREAD

**Issue by pbiecek** [haleyjeppson/ggmosaic#46]
A great package!
Do you know why I don't get the level names on the x nor y axes when I'm done the example from README?

```
ggplot (date = titanic) +
   geom_mosaic(aes(x = product(gender), fill=survived)) 
```

My session info
```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.3

other attached packages:
[1] forcats_0.5.0    patchwork_1.0.1  ggmosaic_0.3.0   ggplot2_3.3.2   
[5] DALEX_1.3.0      kableExtra_1.1.0
```

**Comment by GegznaV** [comment]
@pbiecek,

First, did you mean `data =` (with `a`) instead of `date =` (with `e`)
Next, on my PC, `titanic` dataset is not present (but `Titanic` is). Could you provide a fully functional code as a [reprex](https://www.tidyverse.org/help/#reprex)?

**Comment by pbiecek** [comment]
@GegznaV thank you for very quick response.
I've reinstalled everything, and now the axis labels work.
Thank you for this useful package.

Btw, 
you may consider rebuilding the pkgdown website, 
at https://haleyjeppson.github.io/ggmosaic/ you have still the old variable names
```
ggplot(data = fly) +
  geom_mosaic(aes(x = product(RudeToRecline), fill=DoYouRecline))
```
while in README you have new
```
ggplot(data = fly) +
  geom_mosaic(aes(x = product(rude_to_recline), fill=do_you_recline))
```

**Comment by GegznaV** [comment]
> you may consider rebuilding the pkgdown website,
at https://haleyjeppson.github.io/ggmosaic/ you have still the old variable names

@pbiecek, I tried to address your issue in #47. If it is accepted, the website will be automatically updated each time **ggmosaic** is updated on GitHub.
