### ISSUE TITLE
deprecated feature: `unite_()`

### ISSUE THREAD

**Issue by john-h-carson-jr** [haleyjeppson/ggmosaic#72]
ggplot(data = UCL_minavg_loss_cats) +
+   geom_mosaic(aes(x = product(UCL_minavg_loss, dist_name), fill=UCL_minavg_loss)) +
+   facet_wrap(vars(Minavg_node), labeller = label_both) +
+   theme(axis.text.x = element_text(angle=45, hjust=1)) +
+   labs(x="Generating distribution family", y = "Best UCL",
+        title = "Best UCLs by decision tree node")
Warning message:
`unite_()` was deprecated in tidyr 1.2.0.
ℹ Please use `unite()` instead.
ℹ The deprecated feature was likely used in the ggmosaic package.
  Please report the issue at <https://github.com/haleyjeppson/ggmosaic>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by GegznaV** [comment]
@heike, @haleyjeppson what are the plans for fixing deprecation errors?

If you do not have time to look into those and update the package on CRAN, maybe it is a good time to extend the team of developers who can triage the issues (e.g., this topic is repeated in at least 4 issues: #68, #67, #60) and take care of bug fixes?

**What do you think about that?** Please, let us know asap.

**Comment by heike** [comment]
Artifact introduced by deprecation logic in ggplot2 for change from trans to transform. 
Fixed by commit [8215157](https://github.com/haleyjeppson/ggmosaic/commit/8215157ed1a59861ce839ad487be055dcc2de7ca)
